spring.application.name=registration-service

server.port=8083

spring.datasource.url=jdbc:mysql://localhost:3306/registration_db?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=1512

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

course-service.base-url=http://localhost:8082